### ISSUE TITLE
能否接入socket5配置或者自定义代理openai url配置

### ISSUE THREAD

**Issue by caotao94** [zhayujie/bot-on-anything#100]
如题，像有境外服务器的可以反代openai api接口通过自定义url访问，或者socket5访问

**Comment by RegimenArsenic** [comment]
model参数配置下有正向代理openai.proxy可以配置，反向代理可以用http应用

**Comment by caotao94** [comment]
> model参数配置下有正向代理openai.proxy可以配置，反向代理可以用http应用

正向代理只能是http的吗，我用socket5好像不行

**Comment by RegimenArsenic** [comment]
> > model参数配置下有正向代理openai.proxy可以配置，反向代理可以用http应用
> 
> 正向代理只能是http的吗，我用socket5好像不行

是的，正向目前只能是http

**Comment by caotao94** [comment]
很奇怪，试了 反代openai.api_base也不行，报[WARNING][2023-03-08 18:35:58][log.py:39] - Error communicating with OpenAI: Failed to parse: http://myserverip:port/v1/chat/completion
我在另一个项目 https://github.com/transitive-bullshit/chatgpt-api这样反代apiBaseUrl是没啥问题的，感觉是openai-python的bug，已经给他提了issues

**Comment by zhayujie** [comment]
openai接口不支持 socks5 协议
