### ISSUE TITLE
没有接入个人订阅号，配置url时提示请求url超时

### ISSUE THREAD

**Issue by Mingxiangyu** [zhayujie/bot-on-anything#104]
各位大佬，明明这个链接直接浏览器地址访问是没问题的，这个token也是和config.json中配置的token是一样的，但是总是提示 请求URL超时

**Comment by Mingxiangyu** [comment]
解决了，我的问题是因为公网ip是ipv6，域名没有做备案，所以80端口跟443端口应该是被运营商拦截了，导致微信公众号平台请求我的服务器一直无法成功。换了一个公网ipv4地址，背过案的，公众号就成功连上上了，不过就是公众号总是卡在：正在处理中

**Comment by zhayujie** [comment]
@Mingxiangyu  卡在处理中考虑是openai接口网络不通问题

**Comment by pk350** [comment]
> 解决了，我的问题是因为公网ip是ipv6，域名没有做备案，所以80端口跟443端口应该是被运营商拦截了，导致微信公众号平台请求我的服务器一直无法成功。换了一个公网ipv4地址，背过案的，公众号就成功连上上了，不过就是公众号总是卡在：正在处理中

兄弟怎么换的？我只有ipv6公网，也是请求失败

**Comment by Mingxiangyu** [comment]
换成了云服务器，IPv6不行，应为运营商屏蔽了80端口，而且域名也没法绑定IPv6，所以没法备案，所以IPv6行不通。
> > 解决了，我的问题是因为公网ip是ipv6，域名没有做备案，所以80端口跟443端口应该是被运营商拦截了，导致微信公众号平台请求我的服务器一直无法成功。换了一个公网ipv4地址，背过案的，公众号就成功连上上了，不过就是公众号总是卡在：正在处理中
> 
> 
> 
> 兄弟怎么换的？我只有ipv6公网，也是请求失败
