### ISSUE TITLE
如何限制微信回复内容的长度呢？

### ISSUE THREAD

**Issue by peiyun1982** [zhayujie/bot-on-anything#105]
总有人在群里让GPT写超长的文案。很浪费token。如何限制GPT回复的文字数量呢？比如回答不超过300字。
现在有一个参数`"conversation_max_tokens": 1000,`这个是关联上下文的字数吧？应该不是限制回复字数，这么理解对不？

**Comment by RegimenArsenic** [comment]
是的，要限制回复文字数量，可以在每次输入最后加上”你的回答尽量不要超过300个字“来让chatgpt主动精简回答字数

**Comment by peiyun1982** [comment]
> 是的，要限制回复文字数量，可以在每次输入最后加上”你的回答尽量不要超过300个字“来让chatgpt主动精简回答字数

是这样的，有群友让GPT写文案什么的，就会很长。群友自己并不会主动限制。所以我希望在后台限制GPT不要输出300字以上的内容

**Comment by RegimenArsenic** [comment]
可以在character_desc配置里加上“你的回答尽量不要超过300个字”，但是有时候gpt会忘记这个设定

**Comment by peiyun1982** [comment]
> 可以在character_desc配置里加上“你的回答尽量不要超过300个字”，但是有时候gpt会忘记这个设定

是的，我已经在这里增加了300字设定。而且我还告诉他不要谈论政治，色情等内容。但好像他不怎么听话

**Comment by zhayujie** [comment]
在 chatgpt_model.py 中 加一个 max_token参数
![image](https://user-images.githubusercontent.com/26161723/224485982-3258e4a5-27be-40a2-a41f-0fe27fddc64d.png)

**Comment by peiyun1982** [comment]
> 在 chatgpt_model.py 中 加一个 max_token参数 ![image](https://user-images.githubusercontent.com/26161723/224485982-3258e4a5-27be-40a2-a41f-0fe27fddc64d.png)

“回复的最大次数”？？我的意思是单独一次的回复字数不要太多，而不是回复的“次数”太多。
总之我这样修改试一下效果

**Comment by peiyun1982** [comment]
> 在 chatgpt_model.py 中 加一个 max_token参数 ![image](https://user-images.githubusercontent.com/26161723/224485982-3258e4a5-27be-40a2-a41f-0fe27fddc64d.png)

这个好使！回复的文字确实变短了。
看回复的效果，好像是GPT已经输出了足够多的内容，但是被硬生生截断了。只输出了`max_tokens`里设置的长度的内容，所以终端的很突然。不过这确实解决了我的问题，表示感谢！

顺便……期待企业微信上线中…………
