### ISSUE TITLE
slack模式下订阅url是否必须要求是https？

### ISSUE THREAD

**Issue by includedhj** [zhayujie/bot-on-anything#109]
订阅 URL，如果端口是 80 ，可不填

http:/你的固定公网ip或者域名:端口/slack/events
-----------------------------------------------
slack后台配置要求是https，此处是http？

**Comment by zhayujie** [comment]
需要请教下 @amaoo

**Comment by amaoo** [comment]
可以http，目前就在用http

**Comment by includedhj** [comment]
<img width="816" alt="image" src="https://user-images.githubusercontent.com/6733296/224526117-49f114a9-819c-403b-9572-5da1202a6c3d.png">
@amaoo @zhayujie 
是在这个位置填？看意思就是https

**Comment by amaoo** [comment]
![image](https://user-images.githubusercontent.com/48399388/224546467-6509bf49-513c-4c20-8efb-28d96c294c8c.png)
@includedhj

**Comment by includedhj** [comment]
@amaoo 是我搞错了，多谢解答
