### ISSUE TITLE
企业服务号添加好了，正常开启后只回复“正在思考中...”

### ISSUE THREAD

**Issue by Dfengs** [zhayujie/bot-on-anything#11]
企业服务号添加好了，正常开启后只回复“正在思考中...”
打印日志中显示openai也返回结果了，但是公众号没推送

**Comment by zhayujie** [comment]
企业服务号有 微信认证吗，需要开通客服接口

**Comment by zhayujie** [comment]
<img width="1472" alt="image" src="https://user-images.githubusercontent.com/26161723/219829163-d5452d03-cece-4895-8f7b-d5b57631ce0b.png">

<img width="1784" alt="image" src="https://user-images.githubusercontent.com/26161723/219829192-eecb559d-4a05-4c8b-b800-192d6eaf47e4.png">

**Comment by Dfengs** [comment]
> 企业服务号有 微信认证吗，需要开通客服接口

噢，没认证，我以为已经可以发送“正在思考中...”了，原来这两个是用不同的方式推的。

**Comment by zhayujie** [comment]
是的，一个是回复，一个是主动推

**Comment by Dfengs** [comment]
> 是的，一个是回复，一个是主动推

多谢，我认证一下再试。

**Comment by zhayujie** [comment]
好的，到时候可以重新拉下代码，我修复了一些问题

**Comment by Dfengs** [comment]
认证过了，也重新拉了最新的代码，好像还是不行

**Comment by WangYJian** [comment]
微信认证了客服接口也开了，但是还是只回复“正在思考中”，后台有响应
