### ISSUE TITLE
cq-http 上报事件信息是否可以忽略。避免了报错

### ISSUE THREAD

**Issue by mouyong** [zhayujie/bot-on-anything#114]
![image](https://user-images.githubusercontent.com/10336437/224494236-113a0ddd-69a4-4da5-81fc-60e9039ebf00.png)

**Comment by mouyong** [comment]
关闭了 cq-http 的心跳间隔后，避免了心跳包的发送。

**Comment by zhayujie** [comment]
这个如何关闭

**Comment by mouyong** [comment]
@zhayujie 在 cq-http 的配置里面，搜索 heartbit 可以找到

文档可以增加一个 cq-http 启动对时候，需要修改 devices.json 的 prorocol 为 3。不然会导致说账号冻结。

![image](https://user-images.githubusercontent.com/10336437/224526924-8e35f0d5-c9b9-42c5-8a86-83aa63a49dbb.png)

**Comment by mouyong** [comment]
另一个做法是，bot-on-anything 的接收请求的部分。丢弃掉这个请求的上报。

**Comment by zhayujie** [comment]
> @zhayujie 在 cq-http 的配置里面，搜索 heartbit 可以找到
> 
> 文档可以增加一个 cq-http 启动对时候，需要修改 devices.json 的 prorocol 为 3。不然会导致说账号冻结。

好的，不过应该是 prorocol 改为2吧，用手表登录

**Comment by mouyong** [comment]
protocol 为 3 表示使用 mac 登录。改成 2是不是电脑和端和程序端可以同时在线
