### ISSUE TITLE
关于微信机器人accessToken的问题

### ISSUE THREAD

**Issue by zouzhenglu** [zhayujie/bot-on-anything#118]
继承了werobot后，accessToken我们是否能够管理，另外，我能不能在这个端口上直接开其他接口，这样才能统一管理接口，不然accessToken会抢

**Comment by zhayujie** [comment]
1.accessToken 被 werobot 封装了， 可以看下文档中有没有管理接口
https://werobot.readthedocs.io/zh_CN/latest/client.html#id1

2.目前的设计这个端口监听后不能和其他接口一起工作了

**Comment by zouzhenglu** [comment]
`        app.add_url_rule(rule='/robot/',  # WeRoBot 的绑定地址
                         endpoint='werobot',  # Flask 的 endpoint
                         view_func=make_view(robot),
                         methods=['GET', 'POST'])`
werobot有提供方案，这样就把路径改为robot，而不是直接在域名下了。接下来可以添加用app来开启接口

**Comment by zouzhenglu** [comment]
accessToken可以通过下面获取
`def access_token():
    return robot.client.token
`
