### ISSUE TITLE
请问为什么clash里没有看到对openai的代理

### ISSUE THREAD

**Issue by goxq** [zhayujie/bot-on-anything#123]
### 问题描述
代理已经开启，并且已经在app.py中设置代理
如下图所示
<img width="842" alt="image" src="https://user-images.githubusercontent.com/58415702/224891436-4b1e1e89-8906-4244-9721-74d9205a38bb.png">
<img width="397" alt="image" src="https://user-images.githubusercontent.com/58415702/224891521-3af7ff0e-5b82-434c-afa8-9dcfc390bbe3.png">
<img width="531" alt="image" src="https://user-images.githubusercontent.com/58415702/224891542-f653edfa-72c4-4fee-8680-fdaddfae8936.png">

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/58415702/224891628-eeacebc8-e703-4091-88af-34bb305a23e8.png">
没有看到对openai的代理

bot_on_qq截图：
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/58415702/224891926-53c9a7b3-3494-4bcc-9f4a-a4374d51e047.png">

gocqhttp截图：
<img width="676" alt="image" src="https://user-images.githubusercontent.com/58415702/224891999-e62451ab-2c84-4c0e-b184-e96d98827103.png">

**Comment by goxq** [comment]
@zhayujie 请求大佬来看下🥹

**Comment by goxq** [comment]
@zhayujie 已经解决。用terminal channel试了一下，发现忘记安装openai（pip install openai），安装后可以了。在qq的channel下貌似没有此提示，可以考虑添加一下。
Thx

**Comment by zhayujie** [comment]
@goxq  好的， 因为 oepnai的依赖是在选择模型那一步就需要安装的， channel 部分就没有再说明了
