### ISSUE TITLE
本地vsc上运行代码module 'werobot' has no attribute 'WeRoBot'

### ISSUE THREAD

**Issue by leige818** [zhayujie/bot-on-anything#125]
小白，配置都改过了，代码在服务器上对接微信服务号之后功能正常，自己想加一些代码上去，在本地用vscode运行就报了异常，提示缺少的werobot我从其他地方下载放在网站目录运行后问题依旧，不知道怎么个情况，实际上我把自己加的代码删掉运行也是这个提示，而且形同代码服务器能运行。
请大佬帮看下
![python-error](https://user-images.githubusercontent.com/116787657/224911726-70626f31-7c5a-41d8-a2be-f9e9ce7ac069.png)

**Comment by RegimenArsenic** [comment]
你的python环境没装werobot，在你的python环境里执行pip3 install werobot

**Comment by leige818** [comment]
> 你的python环境没装werobot，在你的python环境里执行pip3 install werobot

谢谢指导，这会正在本地环境安装pip然后操作。

**Comment by leige818** [comment]
安装了pip重新安装依赖后本地可以正常启动了。谢谢
