### ISSUE TITLE
可以提供docker内支持吗

### ISSUE THREAD

**Issue by kingofpowers** [zhayujie/bot-on-anything#14]
跑了一下微信公众号配置，发现监听的是127.0.0.1，在docker里无法生效，调整channel/wechat/wechat_mp_channel.py  WechatSubsribeAccount startup方法添加        robot.config['HOST'] = '0.0.0.0'就可以正常工作了

**Comment by zhayujie** [comment]
已修改，默认监听0.0.0.0

**Comment by nmydt** [comment]
@kingofpowers 为什么我是0.0.0.0也不行，不用docker就行了
