### ISSUE TITLE
公众号无法正常回复消息

### ISSUE THREAD

**Issue by stakeswky** [zhayujie/bot-on-anything#144]
问题：用户向公众号发送你好，公众号回复“正在思考中”后便无响应
log：[INFO][2023-03-15 23:30:30][wechat_mp_service_channel.py:13] - [WX_Public] receive public msg: 你好, userId: oda_X6MZUt9RLBI4iboSBuU6_lQQ
175.24.214.150 - - [15/Mar/2023 23:30:30] "POST /wx?signature=8fc817ee637fa1dc951e97ee95196ab0f8584bcc&timestamp=1678937430&nonce=1969347785&openid=oda_X6MZUt9RLBI4iboSBuU6_lQQ HTTP/1.1" 200 291
[INFO][2023-03-15 23:30:30][log.py:32] - [CHATGPT] query=你好
[INFO][2023-03-15 23:30:38][log.py:34] - [CHATGPT] reply=你好！有什么我能帮你解答或解决的问题吗？
[INFO][2023-03-15 23:30:38][wechat_mp_service_channel.py:35] - [WX_Public] reply content: 你好！有什么我能帮你解答或解决的问题吗？
平台信息：阿里云河源，Ubuntu20.04，python3.8.10

**Comment by zhayujie** [comment]
是不是服务号没有开通客服接口

**Comment by goxofy** [comment]
@zhayujie 您好，个人公众号多人关注的话，同时发消息，各自的上下文是独立的吗？

**Comment by stakeswky** [comment]
> 是不是服务号没有开通客服接口

原来是我没有认证公众号

**Comment by zhayujie** [comment]
> @zhayujie 您好，个人公众号多人关注的话，同时发消息，各自的上下文是独立的吗？

会话上下文是独立的
