### ISSUE TITLE
手动打包部署的方式部署前端 修改.env 文件中的 VITE_APP_API_BASE_URL 为实际后端接口地址 不生效

### ISSUE THREAD

**Issue by lizhongyuan3** [zhayujie/bot-on-anything#149]
<img width="816" alt="image" src="https://user-images.githubusercontent.com/44236581/225661874-d8c2ef6f-d56b-4ae5-a069-1cb4958b61d8.png">
修改之后配置nginx 为
<img width="435" alt="image" src="https://user-images.githubusercontent.com/44236581/225662668-59d95631-da0b-473c-baeb-144e454dff2a.png">
实际访问接口的时候
<img width="719" alt="image" src="https://user-images.githubusercontent.com/44236581/225662906-d99a0aba-3304-4c4a-9881-16226d00d4fb.png">
所以是不是打包的时候设置 VITE_APP_API_BASE_URL 无效

**Comment by zhayujie** [comment]
应该不是这个项目哈
