### ISSUE TITLE
接入到公众号运行成功，但是公众号测试无法正常

### ISSUE THREAD

**Issue by chana1234212** [zhayujie/bot-on-anything#150]
还在处理中，请稍后再试

公众号只回复了上面这句，无法调用成功，这是什么情况？？是缺少什么配置吗？

@zhayujie

**Comment by chana1234212** [comment]
@zhayujie  运行成功这样子，没报错的
[root@iZt4neswmrcgy0m7d10cu0Z bot-on-anything]# python3
Python 3.6.8 (default, Apr 16 2020, 01:36:27)
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> c
[1]+  Stopped                 python3
[root@iZt4neswmrcgy0m7d10cu0Z bot-on-anything]# python3 app.py
载入环节
{'model': {'type': 'chatgpt', 'openai': {'api_key': ' 删除了': 'gpt-3.5-turbo', 'proxy': '', 'conversation_max_tokens': 1000, 'character_desc': '你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'}}, 'channel': {'type': 'wechat_mp', 'wechat_mp': {'token': '删除了', 'port': '80'}}}
[INFO][2023-03-17 10:45:25][log.py:34] - [INIT] Start up: chatgpt on wechat_mp
[INFO][2023-03-17 10:45:25][wechat_mp_channel.py:44] - [WX_Public] Wechat Public account service start!
Bottle v0.12.25 server starting up (using AutoServer())...
Listening on http://0.0.0.0:80/
Hit Ctrl-C to quit.

**Comment by jhavie** [comment]
你需要输入“继续”以获取回复 具体是因为公众号15s超时限制 
https://github.com/zhayujie/bot-on-anything/issues/23
https://github.com/zhayujie/bot-on-anything/pull/24/commits/b67617a04a0e741a323e1aa9dd58fe8805e096a6?diff=split&w=0

**Comment by chana1234212** [comment]
输入了继续，等了几分钟都没有内容出来，只有处理中，大佬能不能帮忙看看？  用着香港服务器或新加坡，美国试过了。
@jhavie

**Comment by jhavie** [comment]
你可以尝试设置proxy代理再试试
<img width="861" alt="image" src="https://user-images.githubusercontent.com/30374119/225802201-437119a0-2c69-4b0f-8cd8-a2357390241a.png">

**Comment by chana1234212** [comment]
这个也试过的， 重点是运行成功了，但是不能回复内容！
@jhavie

**Comment by chana1234212** [comment]
[](url)

**Comment by chana1234212** [comment]
不好说，没人能说下怎么解决



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月05日 01:12 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [zhayujie/bot-on-anything] 接入到公众号运行成功，但是公众号测试无法正常 (Issue #150) |

同样的问题，不知道最后有没有解决
