### ISSUE TITLE
这个微信二维码一直刷新怎么办？

### ISSUE THREAD

**Issue by Mort1f** [zhayujie/bot-on-anything#17]
登录需要等5秒，这个不到5秒就刷新了，登录不了微信

**Comment by zhayujie** [comment]
参考这个issue 该一行代码哈
https://github.com/zhayujie/chatgpt-on-wechat/issues/8

**Comment by Mort1f** [comment]
> 参考这个issue 该一行代码哈 [zhayujie/chatgpt-on-wechat#8](https://github.com/zhayujie/chatgpt-on-wechat/issues/8)
感谢大佬，二维码可以扫了，不过还是登录不了。
![图片](https://user-images.githubusercontent.com/45186522/220259643-3b4b23a2-7c71-4da8-852c-70270ddb417d.png)
他又提示这个错误是什么意思？

**Comment by zhayujie** [comment]
有安装itchat-uos吗

执行下
pip3 show itchat-uos
pip3 show itchat 

个人微信的话这里有详细文档:https://github.com/zhayujie/chatgpt-on-wechat

**Comment by Mort1f** [comment]
![图片](https://user-images.githubusercontent.com/45186522/220369573-123c35d7-254f-4c47-b61f-82b7554880e5.png)

**Comment by zhayujie** [comment]
安装的版本没问题，看来是wx有限制
