### ISSUE TITLE
请教问题：能否使用自己训练后的私有模型

### ISSUE THREAD

**Issue by bmrainc** [zhayujie/bot-on-anything#179]
我自己训练个模型，然后修改配置model，能正常使用吗？

**Comment by zhayujie** [comment]
你的模型是在openai的playgroud吗？还是你完全自己训练的

**Comment by bmrainc** [comment]
> 你的模型是在openai的playgroud吗？还是你完全自己训练的

是完全我自己训练的，微调模型

**Comment by bmrainc** [comment]
我改成自己训练的模型后，报错。
![image](https://user-images.githubusercontent.com/7332588/227734517-50d6f08b-ba9a-4ed9-9075-d87bd77dc003.png)

**Comment by zhayujie** [comment]
这个不是模型的问题， 看起来像网络的问题。 model参数用默认的可以通吗

**Comment by bmrainc** [comment]
用默认的gpt-3.5-turbo可以通。是否不同模型返回的数据格式不一样，导致chatgpt_model.py处理报错

**Comment by bmrainc** [comment]
自己训练的微调模型，返回的数据如下：{"id":"xxx","object":"text_completion","created":1679767824,"model":"xxxx","choices":[{"text":"xxxx","index":0,"logprobs":null,"finish_reason":"length"}],"usage":{"prompt_tokens":11,"completion_tokens":49,"total_tokens":60}}

**Comment by bmrainc** [comment]
貌似找到问题了，我用curl请求的url是/v1/completions。日志打印的请求是/v1/chat/completions。请求地址可以改吗

**Comment by zhayujie** [comment]
@bmrainc   gpt3.5 用的是  /v1/chat/completions,   gpt3.0 用的是 /v1/completions 

你可以在 bridge.py 里面 ，把你的模型加在 列表里
<img width="799" alt="image" src="https://user-images.githubusercontent.com/26161723/227755012-2f6b5988-693d-4102-b32c-06dc4b722073.png">

**Comment by bmrainc** [comment]
你好，之前config里面的type没配置openai，导致请求的地址，错误。该问题已解决。但是我配置了私有模型之后，返回的答案还是标准模型的

**Comment by bmrainc** [comment]
看代码，是在open_ai_model.py里面写死了？
![image](https://user-images.githubusercontent.com/7332588/227789672-4da4be7e-bc80-4954-ad37-49fb53d8307f.png)

**Comment by bmrainc** [comment]
的确是改了这里就行。可以设置成从配置里面获取。
