### ISSUE TITLE
建议接入Edge GPT的ImageGen（BingImageCreator接口）

### ISSUE THREAD

**Issue by linmp4** [zhayujie/bot-on-anything#187]
反编译new bing接口的Edge GPT，生成图像ImageGen已经接入了Bing Image Creator接口了。
$ python3 -m ImageGen -h
usage: ImageGen.py [-h] [-U U] [--cookie-file COOKIE_FILE] --prompt PROMPT [--output-dir OUTPUT_DIR]

options:
  -h, --help            show this help message and exit
  -U U                  Auth cookie from browser
  --cookie-file COOKIE_FILE
                        File containing auth cookie
  --prompt PROMPT       Prompt to generate images for
  --output-dir OUTPUT_DIR
                        Output directory

**Comment by kettly1260** [comment]
https://github.com/acheong08/EdgeGPT
已经集成在EdgeGPT了好像，应该可以直接调用

**Comment by linmp4** [comment]
> dgeGPT

对喔，我改改

**Comment by kettly1260** [comment]
bing长时间没有会话会无法连接，需要重新启动才可以

**Comment by RegimenArsenic** [comment]
#197 #200 已实现,需要更新EdgeGPT
