### ISSUE TITLE
80端口一直被“system”系统程序占用，用反向代理也是无法监听80端口

### ISSUE THREAD

**Issue by arron123456** [zhayujie/bot-on-anything#189]
![image](https://user-images.githubusercontent.com/38456883/226957491-bef8df82-5eaf-4e22-a748-e07664895f60.png)

**Comment by zhayujie** [comment]
你现在想启动什么channel呢， 换一个port可以不

**Comment by arron123456** [comment]
微信公众号，好像必须要80端口，不接受ip:port的形式

**Comment by arron123456** [comment]
> 你现在想启动什么channel呢， 换一个port可以不
> 
> see #173

wechat_mp_sevices

**Comment by JamalHanGit** [comment]
> > 可以关掉这个80的系统进程嘛，好像没别的好办法了
> 
> 阿里云的win服务器好像都占用80，关不掉，已经换了ubuntu,80端口的问题解决了

你这个Ubuntu的怎么解决的？是换了Ubuntu就好了吗？
