### ISSUE TITLE
微信订阅号，一直超时，收不到消息

### ISSUE THREAD

**Issue by ConardLi** [zhayujie/bot-on-anything#190]
![image](https://user-images.githubusercontent.com/30708545/227113354-f0b29448-6b86-4a8a-aeef-73f7fd3c9ade.png)

**Comment by arron123456** [comment]
先调整channel为命令行试一下是否正常呢

**Comment by ZealerG** [comment]
> ![image](https://user-images.githubusercontent.com/30708545/227113354-f0b29448-6b86-4a8a-aeef-73f7fd3c9ade.png)

我也是这样 不知道啥情况 命令行的话也不行 毫无回应
![image](https://user-images.githubusercontent.com/68468184/227430331-e662ffef-02de-4f9c-8578-1cd23f153c14.png)

**Comment by arron123456** [comment]
你可以去platform.openai检查下你的openai的api配置，还有服务器ip能否访问chatgpt，和你的config文件gpt模型选对了没

**Comment by ZealerG** [comment]
> 你可以去platform.openai检查下你的openai的api配置，还有服务器ip能否访问chatgpt，和你的config文件gpt模型选对了没

换了个key就可以了

**Comment by Lucas-luwh** [comment]
我也是这个问题，一直超时  咋回事  代理了也没效果

**Comment by wilsonleeee** [comment]
我也是

**Comment by szc040133** [comment]
我也是这个问题 请问是怎么解决的？

**Comment by szc040133** [comment]
> -你怎么解决的？

**Comment by ConardLi** [comment]
> 我也是这个问题 请问是怎么解决的？

就像作者说的，先切到命令行模式，有具体报错
