### ISSUE TITLE
http 报错  http  * Serving Flask app 'channel.http.http_channel'  * Debug mode: off Permission denied

### ISSUE THREAD

**Issue by john35** [zhayujie/bot-on-anything#192]
Load config success
[INFO][2023-03-23 07:46:15][log.py:34] - [INIT] Start up: chatgpt on http
 * Serving Flask app 'channel.http.http_channel'
 * Debug mode: off
Permission denied

**Comment by john35** [comment]
换个端口

**Comment by hellger** [comment]
同样的问题。更改端口无效
