### ISSUE TITLE
公众号，敏感词检测异常

### ISSUE THREAD

**Issue by 6vision** [zhayujie/bot-on-anything#202]
在sensitive_words.txt内粘贴https://github.com/cjh0613/tencent-sensitive-words/blob/main/sensitive_words_lines.txt，公众号一直回复敏感词汇，目测是检测到输入内容与词库两个及以上匹配就报敏感词汇

**Comment by zhayujie** [comment]
我更新了下，拉下最新代码再试试

**Comment by 6vision** [comment]
> 我更新了下，拉下最新代码再试试

刚刚重新下载的项目，现在sensitive_words.txt内为空，提问任何内容都提示敏感词汇，，，，，

**Comment by 6vision** [comment]
> > 我更新了下，拉下最新代码再试试
> 
> 刚刚重新下载的项目，现在sensitive_words.txt内为空，提问任何内容都提示敏感词汇，，，，，



> 我更新了下，拉下最新代码再试试

重新部署的，默认情况下sensitive_words.txt为空，输入任何问题都提示敏感词汇，但在txt文件加入敏感词汇后可以正常使用了，应该是还有些逻辑bug

**Comment by zhayujie** [comment]
@6vision 嗯嗯，我修改了下，原来没有对空行进行处理

**Comment by 6vision** [comment]
感谢。感谢，甚是好用，现在想学学这方面的，可以些许二次开发，现在接入这个之后，自动回复，菜单功能暂时不能用！后期有对这个方面继续开发的打算么？
