### ISSUE TITLE
使用terminal 模式时，报错以下内容？

### ISSUE THREAD

**Issue by ronaldinho1000** [zhayujie/bot-on-anything#22]
Please input your question
User:
nihao
Bot:
[ERROR][2023-02-21 17:44:39][log.py:50] - Internal server error {
    "error": {
        "message": "Internal server error",
        "type": "auth_subrequest_error",
        "param": null,
        "code": "internal_error"
    }
}

**Comment by ronaldinho1000** [comment]
我当前的网络是支持国内国外上网的

**Comment by ronaldinho1000** [comment]
好像是model="text-davinci-003", 这个接口对应的服务器崩溃了；
更换成：model="text-davinci-002",  就好了；

**Comment by zhayujie** [comment]
> 好像是model="text-davinci-003", 这个接口对应的服务器崩溃了； 更换成：model="text-davinci-002", 就好了；

现在已经恢复了

**Comment by ronaldinho1000** [comment]
done
