### ISSUE TITLE
http支持通过api访问吗？

### ISSUE THREAD

**Issue by bmrainc** [zhayujie/bot-on-anything#221]
不通过网页访问，通过api的post请求。
尝试了下，不行，是否因为需要登录鉴权导致？如果是，有无其他方法规避，比如：如何关闭鉴权？
感谢！！！

**Comment by RegimenArsenic** [comment]
是的，api是需要鉴权的，不建议关闭鉴权，不然被扫描到之后很可能会被滥用浪费tokens，鉴权可以先post /login获取Authorization的cookies，后续请求/chat加上获取到的cookies就行了，授权期限是10小时，可以在channel\http\auth.py里修改payload的exp属性来修改授权期限。

>但是，你既然都有openai的apikey了，为什么不直接请求openai的api？而要再转一道http的api呢？

**Comment by bmrainc** [comment]
![image](https://user-images.githubusercontent.com/7332588/228488815-0ddf7d8e-d177-477c-8823-86a9b1179646.png)
postman怎么返回404，url没有错。

**Comment by bmrainc** [comment]
![image](https://user-images.githubusercontent.com/7332588/228489205-93817b22-809a-46cd-9559-c030c4b988f8.png)
postman提示404，url地址应该没错。

**Comment by bmrainc** [comment]
你既然都有openai的apikey了，为什么不直接请求openai的api？而要再转一道http的api呢？

才看到这句话，按说直接请求openai会合适些。
