### ISSUE TITLE
【网页版】请教下本地有代理但程序无法连接api.openai.com如何解决？

### ISSUE THREAD

**Issue by jihaonan** [zhayujie/bot-on-anything#241]
**============报错日志============**
[INFO][2023-04-01 13:39:26][log.py:34] - [INIT] Start up: chatgpt on http
 * Serving Flask app 'channel.http.http_channel'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
Press CTRL+C to quit
127.0.0.1 - - [01/Apr/2023 13:39:33] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2023 13:39:33] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [01/Apr/2023 13:39:35] "POST /login HTTP/1.1" 301 -
127.0.0.1 - - [01/Apr/2023 13:39:35] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Apr/2023 13:39:35] "GET /static/1.css HTTP/1.1" 304 -
127.0.0.1 - - [01/Apr/2023 13:39:35] "GET /static/1.js HTTP/1.1" 304 -
[INFO][2023-04-01 13:39:38][log.py:32] - [CHATGPT] query=？
127.0.0.1 - - [01/Apr/2023 13:39:38] "CONNECT api.openai.com:443 HTTP/1.0" 404 -
127.0.0.1 - - [01/Apr/2023 13:39:38] "CONNECT api.openai.com:443 HTTP/1.0" 404 -
[WARNING][2023-04-01 13:39:38][log.py:39] - Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 404 NOT FOUND')))
127.0.0.1 - - [01/Apr/2023 13:39:38] "CONNECT api.openai.com:443 HTTP/1.0" 404 -
[WARNING][2023-04-01 13:39:38][log.py:39] - [CHATGPT] APIConnection failed
127.0.0.1 - - [01/Apr/2023 13:39:38] "POST /chat HTTP/1.1" 200 -
**============页面响应============**
![image](https://user-images.githubusercontent.com/14744832/229268084-8ebe38d5-d35e-480b-aef0-5ae3cdb97051.png)
**============浏览器直接访问api.openai.com============**
![image](https://user-images.githubusercontent.com/14744832/229268161-bade1390-76ec-427d-8df5-ba83287c3ce7.png)

**Comment by RegimenArsenic** [comment]
配置文件里模型openai里添加参数"proxy": "你本地代理监听地址",

**Comment by jihaonan** [comment]
配置了还是不成
![image](https://user-images.githubusercontent.com/14744832/229268996-20c740ff-8eb2-4520-822e-1694a7ec76d1.png)

**Comment by RegimenArsenic** [comment]
新报错是连接不到你的代理,你看你代理地址和端口对不对

**Comment by jihaonan** [comment]
> 新报错是连接不到你的代理,你看你代理地址和端口对不对

请问下这个可以如何查询到？我是从proxy app的proxy.pac里面查到的，看起来不是这个
![image](https://user-images.githubusercontent.com/14744832/229269533-f0317319-051e-41f2-90f9-b1fb498c35d4.png)
