### ISSUE TITLE
对接个人订阅号启动后报错

### ISSUE THREAD

**Issue by zken2002** [zhayujie/bot-on-anything#253]
![1680448593877](https://user-images.githubusercontent.com/35671318/229362132-6488716e-52c1-46ea-a439-649ea23009a4.png)
请大佬解惑

**Comment by zken2002** [comment]
用的AWS服务器，端口全打开了

**Comment by RegimenArsenic** [comment]
80端口需要root权限,用sudo执行试试

**Comment by zken2002** [comment]
> 80端口需要root权限,用sudo执行试试

谢谢老哥，我加了sudo，如下
![1680453034241](https://user-images.githubusercontent.com/35671318/229366098-ab299c6b-20a4-43fa-ab8d-c823da64ac6d.png)

**Comment by zken2002** [comment]
取得root权限后成功运行，谢谢
