### ISSUE TITLE
公众号配置服务器地址，请求url超时问题

### ISSUE THREAD

**Issue by explorerJi** [zhayujie/bot-on-anything#27]
服务器地址 (URL) 配置： 如果在浏览器上通过配置的URL 能够访问到服务器上的Python程序 (默认监听8088端口)，则说明配置有效。由于公众号只能配置 80/443端口，可以修改配置为直接监听 80 端口 (需要sudo权限)，或者使用反向代理进行转发 (如nginx)。 根据官方文档说明，此处填写公网ip或域名均可。

公众号配置服务器地址这总返回请求url超时，启动不了，是怎么回事？大佬们

**Comment by explorerJi** [comment]
已经解决了，是端口和服务器外部访问的问题。但是现在产生了另外一个问题。就是每次都需要输入“继续”两个字，才能得到回复，这是不是代码就这样实现的逻辑！！！是为了那个5s延长道15s的解决方案吗？

**Comment by YueyulinRU** [comment]
请问你是如何找出是端口和服务器访问的问题的？怎么解决呢，谢谢
