### ISSUE TITLE
http后台有正常reply，但是前端一直显示“网络故障，对话未送达”

### ISSUE THREAD

**Issue by shepardliu2209** [zhayujie/bot-on-anything#276]
在http模式下，后台可以看到有稳定的reply，但是WEB前台一直显示网络故障，对话未送达（基本上1min能返回）
即便是询问比较简单的英文问题，即后台30s左右即可返回答案，但是WEB前台仍显示“网络故障，对话未送达”。
在http模式下，相关的timeout设定参数是多少？ 在1.js中看到有个60000，已改为120000，但是没作用。
![image](https://user-images.githubusercontent.com/84884368/230727890-aff99bae-e2b5-4d5f-86be-4755615dc4bf.png)
![image](https://user-images.githubusercontent.com/84884368/230727926-7d25f3ee-b4b8-4061-a2ca-4b879fad6a5a.png)

**Comment by RegimenArsenic** [comment]
流式对话能正常返回吗？

**Comment by shepardliu2209** [comment]
对的，流式对话基本能正常返回的。。就是这个“网络故障，对话未送达”出现的频率有些高。

**Comment by RegimenArsenic** [comment]
js里设置的是3分钟才超时，你可以看下devTools响应里的报错是超时吗？或者你可以在网页上将回复模式改成流式对话看看能不能正常返回

**Comment by zoukun120** [comment]
我用macos的chrome会有这个现象，单用iphone的chrome就正常，不会出现这个问题

**Comment by zoukun120** [comment]
> 
chrome f12 console控制台中显示502错误：
POST http://117.50.192.191/chat 502 (Bad Gateway)
