### ISSUE TITLE
微信公众号对接成功后，需要用户输入“继续”才能得到结果，用户体验比较差，比较麻烦，怎么解决这个问题？

### ISSUE THREAD

**Issue by explorerJi** [zhayujie/bot-on-anything#28]
已经了，是和服务器的问题但是但是产生另外一一个个个问题问题。。就就就是是是每次都都需要输入输入输入继续继续继续继续继续继续继续继续继续两两两是为了那个5s延长到15s的解决方案吗？

**Comment by BraelynLuz** [comment]
Same problem

**Comment by explorerJi** [comment]
你好，我看有的公号对接了openai api的GPT3.5API,请问咱们目前接的是3.0版本（服务器中查看openai的pathon包及版本号显示Name: openai Version: 0.26.5）对吧，怎样提升至3.5甚至更高呢呢？是不是需要购买openai的付费版才能升级？

**Comment by explorerJi** [comment]
这个公号：https://mp.weixin.qq.com/s/yfqx2BjYk0bpiEP1yDjlqQ，刚升级的3.5，我想升级这个版本需要怎么做呢？

**Comment by Ratten-fanger** [comment]
> 这个公号：[https://mp.weixin.qq.com/s/yfqx2BjYk0bpiEP1yDjlqQ，刚升级的3.5，我想升级这个版本需要怎么做呢？](https://mp.weixin.qq.com/s/yfqx2BjYk0bpiEP1yDjlqQ%EF%BC%8C%E5%88%9A%E5%8D%87%E7%BA%A7%E7%9A%843.5%EF%BC%8C%E6%88%91%E6%83%B3%E5%8D%87%E7%BA%A7%E8%BF%99%E4%B8%AA%E7%89%88%E6%9C%AC%E9%9C%80%E8%A6%81%E6%80%8E%E4%B9%88%E5%81%9A%E5%91%A2%EF%BC%9F)

已经更新到3.5的模型了，见  #51

**Comment by explorerJi** [comment]
我重新克隆拉取了一下代码，对话还是那样，没有任何变化，是我哪里弄错了吗？

**Comment by zhayujie** [comment]
> 我重新克隆拉取了一下代码，对话还是那样，没有任何变化，是我哪里弄错了吗？

参考 https://github.com/zhayujie/bot-on-anything/pull/51 的步骤

**Comment by zhayujie** [comment]
see #继续
