### ISSUE TITLE
如何修改可以go-http 模拟登录弄QQ版的，添加新的moudel或者type就行吗，还需要看哪个文件

### ISSUE THREAD

**Issue by knigth95** [zhayujie/bot-on-anything#29]

**Comment by zhayujie** [comment]
qq 版的需要增加实现

**Comment by zhayujie** [comment]
@knigth95  已经可以支持了，运行go-cqhttp后，修改channel的type即可，文档中已更新

**Comment by knigth95** [comment]
大佬牛逼，我学习学习这个代码发自我的手机-------- 原始邮件 --------发件人： zhayujie ***@***.***>日期： 2023年2月28日周二 01:06收件人： zhayujie/bot-on-anything ***@***.***>抄送： knight_zzm ***@***.***>, Mention ***@***.***>主    题： Re: [zhayujie/bot-on-anything] 如何修改可以go-http 模拟登录弄QQ版的，添加新的moudel或者type就行吗，还需要看哪个文件 (Issue #29)

@knigth95  已经可以支持了，运行go-cqhttp后，修改channel的type即可，文档中已更新
