### ISSUE TITLE
尝试接入bard报错

### ISSUE THREAD

**Issue by piper-1136** [zhayujie/bot-on-anything#291]
~/bot-on-anything# python3 app.py 
Traceback (most recent call last):
  File "app.py", line 9, in <module>
    from plugins.plugin_manager import PluginManager
  File "/root/bot-on-anything/plugins/__init__.py", line 4, in <module>
    from plugins.plugin_registry import PluginRegistry
  File "/root/bot-on-anything/plugins/plugin_registry.py", line 23
    logger.info(f"Plugin {name}_v{plugin_cls.version} registered")
                                                                                                  ^
SyntaxError: invalid syntax
~/bot-on-anything#

**Comment by piper-1136** [comment]
报错位置在最后一个 “

**Comment by RegimenArsenic** [comment]
我这复现不了这个错误，看代码也没问题，感觉可能是python版本的问题

**Comment by zhayujie** [comment]
我也没有复现

**Comment by piper-1136** [comment]
确实是版本问题
