### ISSUE TITLE
微信公众号如何获取token（我用个人订阅号和微信公众号接口一不一样），怎么看是否接收成功信息，订阅号没有反应

### ISSUE THREAD

**Issue by knigth95** [zhayujie/bot-on-anything#30]

**Comment by zhayujie** [comment]
token是在这里配置的
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/26161723/221231876-407bb6e6-d946-440c-862d-aea40bd8d628.png">

**Comment by knigth95** [comment]
> token是在这里配置的 <img alt="image" width="1200" src="https://user-images.githubusercontent.com/26161723/221231876-407bb6e6-d946-440c-862d-aea40bd8d628.png">

我想再问一下，用内网的IP是不是不行（10.开头那种服务器）

**Comment by zhayujie** [comment]
> > token是在这里配置的 <img alt="image" width="1200" src="https://user-images.githubusercontent.com/26161723/221231876-407bb6e6-d946-440c-862d-aea40bd8d628.png">
> 
> 我想再问一下，用内网的IP是不是不行（10.开头那种服务器）

是的，要用公网ip

**Comment by knigth95** [comment]
对了，我配置公众号后测试，好像不能像微信号那样提供画图，是属于配置成功还是没有升级openai发自我的手机-------- 原始邮件 --------发件人： zhayujie ***@***.***>日期： 2023年2月25日周六 11:17收件人： zhayujie/bot-on-anything ***@***.***>抄送： knight_zzm ***@***.***>, Author ***@***.***>主    题： Re: [zhayujie/bot-on-anything] 微信公众号如何获取token（我用个人订阅号和微信公众号接口一不一样），怎么看是否接收成功信息，订阅号没有反应 (Issue #30)





token是在这里配置的 



我想再问一下，用内网的IP是不是不行（10.开头那种服务器）



是的，要用公网ip

**Comment by zhayujie** [comment]
画图功能 目前公众号还不支持

**Comment by knigth95** [comment]
> 画图功能 目前公众号还不支持
那现在chatgpt-on-wechat封号还严重吗
