### ISSUE TITLE
企业微信部署，接收消息服务器配置失败

### ISSUE THREAD

**Issue by Rogarliu** [zhayujie/bot-on-anything#301]
在接受信息服务其配置时报错openapi回调地址不通过，但是服务器（aws）已经可以正常提问，有没有大佬遇到过？
![image](https://user-images.githubusercontent.com/53483845/231508074-b6f63fb1-8cd9-4571-a5cc-7dd1027bcb50.png)
![image](https://user-images.githubusercontent.com/53483845/231509062-3eedaf8e-f383-4317-bf9f-725730f6f2ae.png)

**Comment by lonny1987** [comment]
这个我会，可以来找我加我87220333VX

**Comment by Rogarliu** [comment]
感谢zhayujie大佬支持，目前问题已解决
1. 需要将config.json中的channel中的type调整为wechat_com；
![image](https://user-images.githubusercontent.com/53483845/231523046-afa1fb10-1dc3-48a3-8c7e-ea77edfda69c.png)
2. 执行app.py前需要安装pip install wechatpy、pip install flask；

**Comment by Rogarliu** [comment]
> 这个我会，可以来找我加我87220333VX

问题已解决，感谢
