### ISSUE TITLE
Gmail 模式启动报错Invalid credentials或Connection timed out

### ISSUE THREAD

**Issue by lzxqaq** [zhayujie/bot-on-anything#32]
我成功接入了微信，但是在Gmail启动时会报错Invalid credentials或Connection timed out。我注册和登陆 openai 都是用的是谷歌邮箱（并不是使用谷歌账号）。我配置代理后报错Invalid credentials，未配置时连接超时。这是什么原因呢？

**Comment by zhayujie** [comment]
因为要访问gmail后台，所以需要能访问外网的环境。  Invalid credentials 可以看下 host_password 配置的对不对
