### ISSUE TITLE
遇到两个问题

### ISSUE THREAD

**Issue by kevinwatson2** [zhayujie/bot-on-anything#34]
1, 用terminal，可以看见对话提示，并输入问题。总是得到如下回答，说我quota用完了，实际上我是首次使用。新生成了一个API_Key也是一样。
Please input your question
User:
Hello
Bot:
[WARNING][2023-02-26 15:12:52][log.py:39] - You exceeded your current quota, please check your plan and billing details.
[WARNING][2023-02-26 15:12:57][log.py:39] - [OPEN_AI] RateLimit exceed, 第1次重试
[WARNING][2023-02-26 15:12:58][log.py:39] - You exceeded your current quota, please check your plan and billing details.

2, 用wechat，可以看见二维码，微信扫码后总是说：Network disconnected. Try again later.

请问这两个分别是什么问题？多谢！

**Comment by zhayujie** [comment]
1.  这个是账号没有额度了，更换key并不能解决， 在 https://platform.openai.com/account/usage 查看可用额度

2.是不是网络问题，需要国内网络环境哈

**Comment by kevinwatson2** [comment]
> 1. 这个是账号没有额度了，更换key并不能解决， 在 https://platform.openai.com/account/usage 查看可用额度
> 
我从来没有使用过，直到目前累计使用还是0，如下图所示：
![image](https://user-images.githubusercontent.com/125107829/221569521-adaa7c7f-fd31-4844-8c26-4d6aff7a372e.png)
> 
> 2.是不是网络问题，需要国内网络环境哈
我的确在美国。为啥必须要求国内的网络环境？

**Comment by zhayujie** [comment]
1.如果有额度 Free trail usage会显示的，正常是这样
<img width="663" alt="image" src="https://user-images.githubusercontent.com/26161723/221597270-151a3417-8563-4ef9-afc7-923a5afc7b8c.png">


2.itchat-uos需要国内环境来访问wx后台

**Comment by kevinwatson2** [comment]
@zhayujie 明白了，不清楚为啥我一直没有额度。谢谢！将来有计划支持国外吗？

**Comment by zhayujie** [comment]
> @zhayujie 明白了，不清楚为啥我一直没有额度。谢谢！将来有计划支持国外吗？

有时候会出现注册账号没有免费额度的，可以再注册一个试试。
wechat 实现外网环境的机器人不太方便，  可以尝试用 terminal、telegram 等其他渠道

**Comment by kevinwatson2** [comment]
> 
> 有时候会出现注册账号没有免费额度的，可以再注册一个试试。 wechat 实现外网环境的机器人不太方便， 可以尝试用 terminal、telegram 等其他渠道
新申请了一个账号就有额度，可以使用Terminal了，谢谢！好像有设置问题，ChatGPT只能回答中文。虽然我说过我这边显示中文有困难，它也同意说英文，但还是坚持说中文。多谢！

**Comment by zhayujie** [comment]
> > 有时候会出现注册账号没有免费额度的，可以再注册一个试试。 wechat 实现外网环境的机器人不太方便， 可以尝试用 terminal、telegram 等其他渠道
> 
> 新申请了一个账号就有额度，可以使用Terminal了，谢谢！好像有设置问题，ChatGPT只能回答中文。虽然我说过我这边显示中文有困难，它也同意说英文，但还是坚持说中文。多谢！

在 character_desc 参数中用英文对他进行设置

**Comment by kevinwatson2** [comment]
> 在 character_desc 参数中用英文对他进行设置

按你说的改成英文以后，ChatGPT就可以根据需要说中英文了。非常感谢！
----------
[INFO][2023-02-27 21:34:02][log.py:34] - [INIT] Start up: openai on terminal

Please input your question
User:
Hello
Bot:
 Hi there! How can I help you?

User:
What is ChatGPT?
Bot:
 ChatGPT is a language model developed by OpenAI. It has been trained on a large dataset of text, allowing it to answer questions, generate text, and engage in conversation with users.

User:
can you say it again in Chinese?
Bot:
你好！ChatGPT是由OpenAI开发的语言模型。它经过大量文本数据的训练，能够回答问题，生成文本，并与用户进行对话。

User:
what the average monthly temperature in Livingston NJ 07039 according to history?
Bot:
 According to historical data, the average monthly temperature in Livingston, NJ 07039 is between 40 and 50 degrees Fahrenheit.

User:
Great! thanks!
Bot:
 You're welcome! Is there anything else I can help you with?

User:
none for now.
Bot:
 OK, let me know if you need anything else!

User:

**Comment by kevinwatson2** [comment]
@zhayujie 有一个建议，能否把terminal对话显示紧凑一点，就是把"Users:“和”Bot :“后的换行去掉？ 我自己可以把”User:“后的换行去掉，但不知道如何把”Bot :“后的换行去掉。我是python新手，不太理解你们的源代码，否则就不在这问了。谢谢！
---现在的显示---
User:
Hello
Bot:
Hi there! How can I help you?
---建议的显示---
User: Hello
Bot: Hi there! How can I help you?

**Comment by ytking** [comment]
一直：提问太快啦，请休息一下再问我吧
[WARNING][2023-04-02 17:18:09][log.py:39] - [CHATGPT] RateLimit exceed, 第1次重试
[WARNING][2023-04-02 17:18:10][log.py:39] - You exceeded your current quota, please check your plan and billing details.
