### ISSUE TITLE
可否支持配置一个三方回调？

### ISSUE THREAD

**Issue by panghujiajia** [zhayujie/bot-on-anything#38]
- bot-on-anything
    - 部署后暴漏一个接口，用来接收问题和id，通过chatgpt拿到问题回复后，调用三方接口进行回调

- 三方
    - 一个回调地址，供bot-on-anything携带chatgpt回复访问

**Comment by zhayujie** [comment]
后面可以考虑，但目前这个项目的定位是直接把模型和应用一起做了，实现一键部署
