### ISSUE TITLE
绕过Bing限制后每一句都会自动重置对话模型

### ISSUE THREAD

**Issue by MC-cookies** [zhayujie/bot-on-anything#383]
如题
这是微软的限制还是程序的bug?
有大佬知道如何解决吗?

**Comment by MC-cookies** [comment]
不绕可以正常使用,但是绕过之后每一句都是对话轮次: 1/20

**Comment by sastpg** [comment]
见[#364 ]，以及[说明](https://sastpg.github.io/computer/AItoApp/#3)

**Comment by MC-cookies** [comment]
不是微软撤回了消息,是每次对话都会重置模型
通俗说就是说一句忘一句

**Comment by MC-cookies** [comment]
而且#清除记忆好像在群聊里不管用

**Comment by MC-cookies** [comment]
![image](https://github.com/zhayujie/bot-on-anything/assets/117754398/538b2b9e-3194-40d9-85bb-119076adf53d)
这是越狱后
![image](https://github.com/zhayujie/bot-on-anything/assets/117754398/029874cb-3c18-4b4d-b414-d0732ef25056)
这是未越狱

**Comment by sastpg** [comment]
。。。老哥我都不知道说什么好了
