### ISSUE TITLE
token验证失败

### ISSUE THREAD

**Issue by colorfbalck** [zhayujie/bot-on-anything#39]
![image](https://user-images.githubusercontent.com/124777439/221587889-005d0cdb-25ee-40dd-bfd0-a1328ceffa14.png)
![image](https://user-images.githubusercontent.com/124777439/221588066-3f67a597-06c8-4e4f-9a21-18d828b43633.png)

**Comment by colorfbalck** [comment]
![image](https://user-images.githubusercontent.com/124777439/221593293-f6d71a25-7a52-4fb1-b8ce-948d424eb988.png)

**Comment by zhayujie** [comment]
ip有加到上面的白名单吗

**Comment by ronaldinho1000** [comment]
> ip有加到上面的白名单吗

我的也是token 一直失败；ip 加到白名单了

**Comment by ronaldinho1000** [comment]
> ip有加到上面的白名单吗

![图片](https://user-images.githubusercontent.com/35184678/221725742-ce9b98a4-a78b-44c0-8b80-b379056f6030.png)
我这边显示的IP 跟你教程里面的不一致，是这个造成的吗？

**Comment by ronaldinho1000** [comment]
> ip有加到上面的白名单吗

![图片](https://user-images.githubusercontent.com/35184678/221726419-2b59b352-d499-4607-85fc-bfa7aa8e93c8.png)
这种一直没有机器人回复，可能是什么原因造成的呢？

**Comment by zhayujie** [comment]
@ronaldinho1000  看下后台日志有没有显示结果返回， 或者有没有报错信息

**Comment by colorfbalck** [comment]
ip加到那个白名单？

**Comment by zhayujie** [comment]
> ip加到那个白名单？

就在你截图的公众号url配置 上面

程序运行完需要在浏览器能访问url，显示以下效果
<img width="537" alt="image" src="https://user-images.githubusercontent.com/26161723/221727188-c872f26b-fae8-4a40-8365-ceca2de4252b.png">

**Comment by colorfbalck** [comment]
加了

**Comment by colorfbalck** [comment]
![image](https://user-images.githubusercontent.com/124777439/221727690-07684b58-5f14-4144-bacb-ed1a27698c4a.png)

**Comment by ronaldinho1000** [comment]
> @ronaldinho1000 看下后台日志有没有显示结果返回， 或者有没有报错信息

![图片](https://user-images.githubusercontent.com/35184678/221727906-92708d25-78d6-4124-aa32-77b38a1ccee0.png)
没有什么信息返回

**Comment by ronaldinho1000** [comment]
> 

![图片](https://user-images.githubusercontent.com/35184678/221728062-4ece4fce-6edc-4894-9222-f9db780edcd2.png)
验证token 时，我手动改动了一点代码，因为这里老是检查token 不匹配，所以我就直接return 了；

**Comment by colorfbalck** [comment]
> 
你token验证失败 怎么解决的？

**Comment by ronaldinho1000** [comment]
> @ronaldinho1000 看下后台日志有没有显示结果返回， 或者有没有报错信息

![图片](https://user-images.githubusercontent.com/35184678/221728581-8e326f8f-4359-4559-8501-70357d231459.png)
这样配置有问题吗？

**Comment by ronaldinho1000** [comment]
> > ip加到那个白名单？
> 
> 就在你截图的公众号url配置 上面
> 
> 程序运行完需要在浏览器能访问url，显示以下效果 <img alt="image" width="537" src="https://user-images.githubusercontent.com/26161723/221727188-c872f26b-fae8-4a40-8365-ceca2de4252b.png">

这个界面我能正常显示

**Comment by colorfbalck** [comment]
我可以正常显示，ip也加入白名单了，但是配置服务器，提示token验证失败
![image](https://user-images.githubusercontent.com/124777439/221729845-82547ebb-f0fc-4641-8a2c-2079b545e4a6.png)
![image](https://user-images.githubusercontent.com/124777439/221729939-4b911020-45ca-4f96-be7d-5cef9669dd9f.png)
![image](https://user-images.githubusercontent.com/124777439/221730280-ea19aaea-fe65-40b5-a122-c7de95f9777d.png)
![image](https://user-images.githubusercontent.com/124777439/221730504-efd58c2b-fb7b-41b4-8530-e525ce351953.png)
![image](https://user-images.githubusercontent.com/124777439/221730600-adc96050-e7a4-4e22-a7af-8f23c6e7492b.png)

**Comment by zhayujie** [comment]
@colorfbalck 你服务器上有运行什么反向代理吗？ 我看浏览器访问werobot页面显示端口是 443，但是实际填的是80

**Comment by zhayujie** [comment]
@ronaldinho1000   把 channel 的type 切到 terminal，在终端试试看openai是不是正常的

**Comment by colorfbalck** [comment]
> @colorfbalck 你服务器上有运行什么反向代理吗？ 我看浏览器访问werobot页面显示端口是 443，但是实际填的是80

内网8088 代理403

**Comment by ronaldinho1000** [comment]
> 

我终端模式是正常的；可以正常使用

**Comment by ronaldinho1000** [comment]
> @ronaldinho1000 把 channel 的type 切到 terminal，在终端试试看openai是不是正常的

![图片](https://user-images.githubusercontent.com/35184678/221740963-6776622a-c035-4aa4-aafa-b26fa3055132.png)

**Comment by zhayujie** [comment]
> > @colorfbalck 你服务器上有运行什么反向代理吗？ 我看浏览器访问werobot页面显示端口是 443，但是实际填的是80
> 
> 内网8088 代理403

直接用80端口可以嘛

**Comment by zhayujie** [comment]
@ronaldinho1000 我晚点跑下试试

**Comment by colorfbalck** [comment]
> > > @colorfbalck 你服务器上有运行什么反向代理吗？ 我看浏览器访问werobot页面显示端口是 443，但是实际填的是80
> > 
> > 
> > 内网8088 代理403
> 
> 直接用80端口可以嘛


直接外网用403端口，提示系统发送错误
![image](https://user-images.githubusercontent.com/124777439/221767554-9cc0a5cd-0f87-479d-bc46-8e555d7cacf9.png)
![image](https://user-images.githubusercontent.com/124777439/221767751-3ed9c034-71f1-4943-98a5-e0044a54b5ff.png)

**Comment by colorfbalck** [comment]
> > > @colorfbalck 你服务器上有运行什么反向代理吗？ 我看浏览器访问werobot页面显示端口是 443，但是实际填的是80
> > 
> > 
> > 内网8088 代理403
> 
> 直接用80端口可以嘛

外网直接用403端扣，提示系统错误。
![企业微信截图_16775645238587](https://user-images.githubusercontent.com/124777439/221768844-a96faa2d-59b1-44c5-8292-ad5b9932f055.png)
![image](https://user-images.githubusercontent.com/124777439/221768888-3e5c16dc-ae29-4ebf-8c7b-0371b1917891.png)

**Comment by colorfbalck** [comment]
切换到企业公众号还是 token错误，后台一直没有收到公众号的请求呢

**Comment by ronaldinho1000** [comment]
> 

微信的token 的验证，例程中是python2 ，如果你本地用的是python3 ，你需要把代码稍微改动一下；
# encoding:utf-8

# filename: handle.py



import hashlib

import web



class Handle(object):

    def GET(self):

        try:

            data = web.input()

            if len(data) == 0:

                return "hello, this is handle view"

            signature = data.signature

            timestamp = data.timestamp

            nonce = data.nonce

            echostr = data.echostr

            token = "123456" #请按照公众平台官网\基本配置中信息填写



            list = [token, timestamp, nonce]

            list.sort()

            sha1 = hashlib.sha1()

            sha1.update(list[0].encode('utf-8'))

            sha1.update(list[1].encode('utf-8'))

            sha1.update(list[2].encode('utf-8'))

            hashcode = sha1.hexdigest()

            print( "handle/GET func: hashcode, signature: ", hashcode, signature)

           # return echostr

            if hashcode == signature:

                return echostr

            else:

                return ""

        except Exception as Argument:

            return Argument

**Comment by colorfbalck** [comment]
> > 
> 
> 微信的token 的验证，例程中是python2 ，如果你本地用的是python3 ，你需要把代码稍微改动一下；
> 
> # encoding:utf-8
> # filename: handle.py
> import hashlib
> 
> import web
> 
> class Handle(object):
> 
> ```
> def GET(self):
> 
>     try:
> 
>         data = web.input()
> 
>         if len(data) == 0:
> 
>             return "hello, this is handle view"
> 
>         signature = data.signature
> 
>         timestamp = data.timestamp
> 
>         nonce = data.nonce
> 
>         echostr = data.echostr
> 
>         token = "123456" #请按照公众平台官网\基本配置中信息填写
> 
> 
> 
>         list = [token, timestamp, nonce]
> 
>         list.sort()
> 
>         sha1 = hashlib.sha1()
> 
>         sha1.update(list[0].encode('utf-8'))
> 
>         sha1.update(list[1].encode('utf-8'))
> 
>         sha1.update(list[2].encode('utf-8'))
> 
>         hashcode = sha1.hexdigest()
> 
>         print( "handle/GET func: hashcode, signature: ", hashcode, signature)
> 
>        # return echostr
> 
>         if hashcode == signature:
> 
>             return echostr
> 
>         else:
> 
>             return ""
> 
>     except Exception as Argument:
> 
>         return Argument
> ```

这修改的是那个文件 没有handle.py呢

**Comment by colorfbalck** [comment]
> > 
> 
> 微信的token 的验证，例程中是python2 ，如果你本地用的是python3 ，你需要把代码稍微改动一下；
> 
> # encoding:utf-8
> # filename: handle.py
> import hashlib
> 
> import web
> 
> class Handle(object):
> 
> ```
> def GET(self):
> 
>     try:
> 
>         data = web.input()
> 
>         if len(data) == 0:
> 
>             return "hello, this is handle view"
> 
>         signature = data.signature
> 
>         timestamp = data.timestamp
> 
>         nonce = data.nonce
> 
>         echostr = data.echostr
> 
>         token = "123456" #请按照公众平台官网\基本配置中信息填写
> 
> 
> 
>         list = [token, timestamp, nonce]
> 
>         list.sort()
> 
>         sha1 = hashlib.sha1()
> 
>         sha1.update(list[0].encode('utf-8'))
> 
>         sha1.update(list[1].encode('utf-8'))
> 
>         sha1.update(list[2].encode('utf-8'))
> 
>         hashcode = sha1.hexdigest()
> 
>         print( "handle/GET func: hashcode, signature: ", hashcode, signature)
> 
>        # return echostr
> 
>         if hashcode == signature:
> 
>             return echostr
> 
>         else:
> 
>             return ""
> 
>     except Exception as Argument:
> 
>         return Argument
> ```

用的python3.10

**Comment by colorfbalck** [comment]
用的python3.10

**Comment by ronaldinho1000** [comment]
你要按照腾讯给的一些例子进行设置一下才行；

**Comment by zhayujie** [comment]
正常情况部署上去就自带token验证的，不需要增加代码的，看下是不是路由配置的问题
