### ISSUE TITLE
为什么要提示 正在思考中...

### ISSUE THREAD

**Issue by zouzhenglu** [zhayujie/bot-on-anything#41]
RT，服务号的这个提示是不是多余的。如果是微信的机制，我们是不是可以直接回复success或者空字符串，这样用户不会收到这样尴尬的消息

**Comment by zhayujie** [comment]
因为有时候回复太慢了，所以先回复一句。  这个文本你可以在代码里很容易修改

后面我做成配置项，不配这个文本就不会回复这一句

**Comment by zouzhenglu** [comment]
回复慢是一回事，我刚才试着在拿到回答后，sleep(5)秒后再返回，结果就没有反应了。
试着把前面的思考中修改成success，“”，删除，结果都是一样，公众号没有提示服务异常，但是也没有回复消息。
这样的话，这句话加了其实也没什么用。
另外，是不是可以把服务号跟公众号的继续结合，如果超过5秒就回复不了的话，让服务号也能用“继续”来获取回答

**Comment by zhayujie** [comment]
> 回复慢是一回事，我刚才试着在拿到回答后，sleep(5)秒后再返回，结果就没有反应了。 试着把前面的思考中修改成success，“”，删除，结果都是一样，公众号没有提示服务异常，但是也没有回复消息。 这样的话，这句话加了其实也没什么用。 另外，是不是可以把服务号跟公众号的继续结合，如果超过5秒就回复不了的话，让服务号也能用“继续”来获取回答

估计公众号的设计就是必须要有一句被动回复， 不然会提示服务异常。   

服务号按现在的设计是不需要通过"继续"来获取的， 因为一定可以完成主动推送

**Comment by zouzhenglu** [comment]
> 你试试time.sleep(5)之后看还能行不。我就是延迟太大导致超过5秒钟，这种情况不容易测试出来，所以加了5秒测试。结果就出不来了。但是正常的情况下，我看走客服接口应该是48小时之内都能发成功的。难道是我还需要在另外配置

**Comment by zouzhenglu** [comment]
发现是自己的问题，关闭了哈，打扰了
