### ISSUE TITLE
TG运行问题

### ISSUE THREAD

**Issue by DwyaneLee** [zhayujie/bot-on-anything#43]
halo，大佬，我想请教下如果像**tg**、**gmail**这些是不是一定要放在有外网的服务器上运行，如果我想在本地电脑开代理运行可以在哪里添加代理呢？
![1677578340145](https://user-images.githubusercontent.com/54064448/221820651-8fb6866b-3c11-4bc1-8d2c-9fb4fbe7e401.png)
上图是我本地开了全局代理后运行提示ssl错误
![1677578409003](https://user-images.githubusercontent.com/54064448/221820865-02db4e2b-c217-4e10-b0c6-76f2d2c437ce.png)
上图是本地关了全局代理后运行提示超时，

**Comment by brucelt1993** [comment]
> 

这个需要部署在外网服务器上，或者 telegram bot api 使用代理来运行，直接跑是不通的，bot api 国内不通

**Comment by zhayujie** [comment]
参考 https://github.com/zhayujie/chatgpt-on-wechat/pull/244

**Comment by zhayujie** [comment]
@brucelt1993  在国能环境的开发机上 开vpn可以用吗

**Comment by DwyaneLee** [comment]
> 

请问怎么让tg bot ai使用代理来运行呢，跳来跳去没找到
