### ISSUE TITLE
给订阅号发消息后台日志没接收到

### ISSUE THREAD

**Issue by Thomas9101** [zhayujie/bot-on-anything#44]
浏览器中能正常访问公网ip，可以出现WeRoBot界面，但是给订阅号发信息没反应
![image](https://user-images.githubusercontent.com/126573159/221898087-6037de36-8baa-4dca-82aa-672a3cd062e0.png)

**Comment by zhayujie** [comment]
订阅号配置url时 token验证能成功吗

**Comment by Thomas9101** [comment]
> 订阅号配置url时 token验证能成功吗

可以验证成功

**Comment by Thomas9101** [comment]
> 订阅号配置url时 token验证能成功吗
sorry~我搞定了，那个配置url我刚才点进去一看，没启用。启用完成就好了，麻烦您了

**Comment by colorfbalck** [comment]
> > 订阅号配置url时 token验证能成功吗
> 
> 可以验证成功

你们验证token能收到消息吗 ，日志有打印吗？
