### ISSUE TITLE
微信公众号，收不到token验证信息呢

### ISSUE THREAD

**Issue by colorfbalck** [zhayujie/bot-on-anything#46]
配置服务器时，收不到验证信息
![image](https://user-images.githubusercontent.com/124777439/222041468-3b8c1ce4-17c4-429e-84b5-aff9a5ff124e.png)

**Comment by zhayujie** [comment]
在URL中配置的地址，  在浏览器中访问可以显示werobot的界面嘛

检查下：
  1. 这个域名有配置反向代理吗， Python程序监听的端口是什么， 能否通过域名访问到程序
  2. token是否配置在 config.json
  3. 服务器ip是否配置在上面的白名单

**Comment by lmmsoft** [comment]
电信会封主要端口，搭在自驾宽带上80 443往往不通

**Comment by colorfbalck** [comment]
> 电信会封主要端口，搭在自驾宽带上80 443往往不通

那你怎么处理的？

**Comment by lmmsoft** [comment]
> > 电信会封主要端口，搭在自驾宽带上80 443往往不通
> 
> 那你怎么处理的？

有ip或者内网穿透啊
