### ISSUE TITLE
为什么我的公众号只能用80或者443端口？

### ISSUE THREAD

**Issue by JarvanDing** [zhayujie/bot-on-anything#6]
我配置了8090端口直接访问显示未响应。
我在公众号配置又只能用80和443端口。

**Comment by zhayujie** [comment]
需要反向代理转发一下，而且需要有域名

比如用nginx配置 80端口 -> 8090 端口

**Comment by bboychencan** [comment]
你这个东西必须要有自己的域名？ 公众号好像可以直接使用ip

**Comment by zhayujie** [comment]
> 你这个东西必须要有自己的域名？ 公众号好像可以直接使用ip

看了下官方文档，应该公网ip也行，文档已更新

<img width="745" alt="image" src="https://user-images.githubusercontent.com/26161723/219851780-7b5d5cac-8f48-4793-8e3e-b994233cdbc7.png">

https://developers.weixin.qq.com/doc/offiaccount/Getting_Started/Overview.html

**Comment by bboychencan** [comment]
还是不行啊，启动了服务后
Bottle v0.12.23 server starting up (using AutoServer())...
Listening on http://127.0.0.1:80/
Hit Ctrl-C to quit.
公众号那边填了ip地址，但是一直显示‘token验证失败’ 但实际上token是一样的

**Comment by zhayujie** [comment]
> 还是不行啊，启动了服务后 Bottle v0.12.23 server starting up (using AutoServer())... Listening on http://127.0.0.1:80/ Hit Ctrl-C to quit. 公众号那边填了ip地址，但是一直显示‘token验证失败’ 但实际上token是一样的

你的80端口有对外暴露吗， 浏览器直接访问公网ip可以看到界面吗

**Comment by bboychencan** [comment]
拉了新代码就可以了，IP好像是要改成0.0.0.0
