### ISSUE TITLE
可以支持语音交互方式吗，比如在微信中语音发送内容给api

### ISSUE THREAD

**Issue by nagaki09** [zhayujie/bot-on-anything#60]

**Comment by zhayujie** [comment]
暂时没有语音接口

**Comment by mouyong** [comment]
@zhayujie 

https://github.com/zhayujie/chatgpt-on-wechat/blob/8fa4041fc2a50013618ac33000a349dcfdebf989/channel/wechat/wechat_channel.py#L50-L54

这个好像实现了微信的语音对接。可以结合在一起吗？

**Comment by mouyong** [comment]
https://github.com/zhayujie/chatgpt-on-wechat/blob/8fa4041fc2a50013618ac33000a349dcfdebf989/channel/wechat/wechat_channel.py#L56-L66

**Comment by zhayujie** [comment]
@mouyong 稍后会同步过来

**Comment by mouyong** [comment]
辛苦大佬了，谢谢 @zhayujie 

大佬方便加微信吗

**Comment by zhayujie** [comment]
> 辛苦大佬了，谢谢 @zhayujie
> 
> 大佬方便加微信吗

可以，主页有联系方式

**Comment by mouyong** [comment]
添加失败了，提示大佬的微信被添加过于频繁

**Comment by zhayujie** [comment]
@mouyong 估计被限制了.. 只能过两天再看看了

**Comment by mouyong** [comment]
好呢。

大佬，反馈个问题。qq 的配置文档部分，没有提到 cq-http 要怎么配置，是否需要开启 cq-http 的 正向 ws 反向 ws, 以及 bot 监听的端口是配置在 cq-http 的哪个services 里面。

**Comment by zhayujie** [comment]
@mouyong  好的，有空补充下。 之前没写是因为 config.yml 已经提供了 http部分的配置，只要填qq号就行了
