### ISSUE TITLE
能否增加一下超长对话

### ISSUE THREAD

**Issue by wzq10314** [zhayujie/bot-on-anything#78]
对于超过4096token能否做个优化谢谢！

**Comment by mithew** [comment]
官方限制了

**Comment by wzq10314** [comment]
> 官方限制了

作者已经在他的另一个项目chatgpt-on-wechat修复了超长对话出现：请再问我一次吧的问题，好像就是只要超过4096就会自动清除早期内容，希望能把这里也更新一下

**Comment by zhayujie** [comment]
已更新，可以获取最新代码试试

**Comment by wzq10314** [comment]
> 已更新，可以获得最新代号测试

感谢大佬！
