### ISSUE TITLE
接口中无返回数据，公众号提示出现故障

### ISSUE THREAD

**Issue by GeorgeGalway** [zhayujie/bot-on-anything#8]
详情请见图，确认ApiKey有效，配置如下
![image](https://user-images.githubusercontent.com/24989842/219343608-0ddb2dd7-0988-47ef-a515-36fd15616345.png)

**Comment by GeorgeGalway** [comment]
> 有安装openai依赖吗
> 
> 暂时没看出问题，可以加下我wx

已加，请通过

**Comment by GeorgeGalway** [comment]
缺少了一条命令 `pip3 install --upgrade openai`
感谢作者的辛苦付出，请有时间加到README.md中吧

**Comment by zhayujie** [comment]
已更新
