### ISSUE TITLE
第一次用Ubuntu，请问在使用python3 app.py后，该怎么回到终端继续运行其他程序呢，或者终止这个程序呢...

### ISSUE THREAD

**Issue by ShowUNow** [zhayujie/bot-on-anything#80]
![image](https://user-images.githubusercontent.com/114962931/222968008-650ca8d8-fda4-4993-bc3b-38e283e75ebc.png)
输入什么也回不到终端了...

关键还不能用...

真的不懂，希望有人能赐教

**Comment by Lancenas** [comment]
> ![image](https://user-images.githubusercontent.com/114962931/222968008-650ca8d8-fda4-4993-bc3b-38e283e75ebc.png) 输入什么也回不到终端了...
> 
> 关键还不能用...
> 
> 真的不懂，希望有人能赐教

Python进程后台运行

**Comment by zhayujie** [comment]
Ctrl+C 可以关闭这个进程。  或者再开一个终端执行别的操作。

另外 你的openai需要升级了

**Comment by ShowUNow** [comment]
> Ctrl+C 可以关闭这个进程。 或者再开一个终端执行别的操作。
> 
> 另外 你的openai需要升级了

感谢大佬，不过您是否清楚在Ubuntu 20.04中使用pip3 install --upgrade openai似乎只能把openai更新到0.20.0是什么情况吗？
![image](https://user-images.githubusercontent.com/114962931/222996578-77d9a3a9-09b1-4cd8-8333-ee3b5f9c0ff3.png)
python版本为3.8.10
pip3版本为23.0.1

**Comment by zhayujie** [comment]
@ShowUNow 试试 pip3 install --upgrade openai==0.27.0 -i https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by ShowUNow** [comment]
> @ShowUNow 试试 pip3 install --upgrade openai==0.27.0 -i https://pypi.tuna.tsinghua.edu.cn/simple

谢谢大佬，引发这个问题的原因似乎是那个云服务器商的pip3安装包的源地址的镜像资源太旧了。而且那个地址我也不会改...
不过我已经放弃使用Ubuntu了，又装回Windows了（好耶
