### ISSUE TITLE
AttributeError: module 'openai' has no attribute 'ChatCompletion'

### ISSUE THREAD

**Issue by Angusvencent** [zhayujie/bot-on-anything#83]
运行报错
[ERROR][2023-03-06 00:26:09][log.py:50] - module 'openai' has no attribute 'ChatCompletion'
Traceback (most recent call last):
  File "/root/bot-on-anything/model/chatgpt/chatgpt_model.py", line 44, in reply_text
    response = openai.ChatCompletion.create(
AttributeError: module 'openai' has no attribute 'ChatCompletion'

**Comment by zhayujie** [comment]
openai 需要升级

pip3 install --upgrade openai
