### ISSUE TITLE
请问什么时候添加重置会话功能

### ISSUE THREAD

**Issue by NickyGu** [zhayujie/bot-on-anything#86]
就想wechat bot里的#清除记忆

**Comment by zhayujie** [comment]
这个支持的，试试看

**Comment by NickyGu** [comment]
> 这个支持的，试试看

你好，触发的指令是什么？比如wechat bot那个repot里面是发送#清除记忆

**Comment by mithew** [comment]
可以自己改的

**Comment by zhayujie** [comment]
> > 这个支持的，试试看
> 
> 你好，触发的指令是什么？比如wechat bot那个repot里面是发送#清除记忆

一样的，就是"#清除记忆"

**Comment by NickyGu** [comment]
不行额，见图片
![image](https://user-images.githubusercontent.com/44493037/223057802-64910db9-96f5-4e83-aaf6-4888d8d8de4d.png)
