### ISSUE TITLE
请问目前有支持上下文关联嘛

### ISSUE THREAD

**Issue by ThiefSYF** [zhayujie/bot-on-anything#96]
在测试终端的时候好像是支持了，测试订阅号的时候像是还无关，是支持了但我提问方式有问题还是用于存储记忆的数组比较小？

**Comment by zhayujie** [comment]
支持的， 订阅号也是支持的，有可能会话超长自动释放了。 可以贴一下问答的记录分析下

**Comment by ThiefSYF** [comment]
> 支持的， 订阅号也是支持的，有可能会话超长自动释放了。 可以贴一下问答的记录分析下

感谢,关于微信订阅号的15秒限制,有没有考虑过比如提交后每秒进行一次查询,如果收到res就直接reply,如果15秒未处理完再采用继续的形式,这样或许可以体验好点？

**Comment by zhayujie** [comment]
是的，这里会优化
